# Generated by Django 5.1.7 on 2025-05-02 13:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building_id', models.CharField(blank=True, help_text="Building ID (e.g., 'EMS' for Engineering and Math Science)", max_length=10, null=True, unique=True)),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classroom_id', models.CharField(blank=True, help_text="Classroom ID (e.g., 'EMS-E190')", max_length=15, null=True, unique=True)),
                ('room_number', models.CharField(max_length=10)),
                ('capacity', models.PositiveIntegerField()),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classrooms', to='admin_dashboard.building')),
            ],
            options={
                'unique_together': {('building', 'room_number')},
            },
        ),
    ]
