# Generated by Django 5.1.7 on 2025-05-05 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='schedule',
        ),
        migrations.AddField(
            model_name='section',
            name='day',
            field=models.CharField(choices=[('MON', 'Monday'), ('TUE', 'Tuesday'), ('WED', 'Wednesday'), ('THU', 'Thursday'), ('FRI', 'Friday'), ('SAT', 'Saturday'), ('SUN', 'Sunday')], max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='section',
            name='time_slot',
            field=models.CharField(choices=[('08:00-09:15', '8:00 AM - 9:15 AM'), ('09:30-10:45', '9:30 AM - 10:45 AM'), ('11:00-12:15', '11:00 AM - 12:15 PM'), ('12:30-13:45', '12:30 PM - 1:45 PM'), ('14:00-15:15', '2:00 PM - 3:15 PM'), ('15:30-16:45', '3:30 PM - 4:45 PM'), ('17:00-18:15', '5:00 PM - 6:15 PM'), ('18:30-19:45', '6:30 PM - 7:45 PM')], max_length=11, null=True),
        ),
    ]
