# Generated by Django 5.1.7 on 2025-05-05 21:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0001_initial'),
        ('courses', '0003_section_capacity_alter_section_day_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='location',
        ),
        migrations.AddField(
            model_name='section',
            name='building',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_dashboard.building'),
        ),
        migrations.AddField(
            model_name='section',
            name='classroom',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_dashboard.classroom'),
        ),
    ]
