# Generated by Django 5.1.7 on 2025-05-05 02:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollment_id', models.CharField(blank=True, help_text="Enrollment ID (e.g., 'S123456-CS201-F202501')", max_length=30, null=True, unique=True)),
                ('date_registered', models.DateTimeField(auto_now_add=True)),
                ('grade', models.CharField(blank=True, max_length=2, null=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.section')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.student')),
            ],
            options={
                'unique_together': {('student', 'section')},
            },
        ),
    ]
